# Site settings
title: Margin Notes
description: A blog
url: "https://sambilheimer.github.io/legendary-chainsaw"
baseurl:
mode: dark

# Collection setting
collections:
  posts:
    output: true

# Build settings
# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

# Profile settings
author:
  name: Sam # author name
  # bio: >- # tell to the world
  #  a bio goes here
  username: Haiku # general username
  github: github_username # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: your-email@email.com # email adress
  avatar: /assets/images/water_v1.webp # change with your own avatar

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false
# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5
