# Site settings
title: Margin Notes
description: A blog
url: "https://sambilheimer.github.io" 
baseurl: "/legendary-chainsaw" 

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:year/:month/:day/:title/
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
